# Site
name: '能无知乎'
description: '最精典的宗教书籍，最具特色的解读。'
logo: 'assets/images/logo.png'
logotext: 'assets/images/能无知乎.png'
favicon: 'assets/images/china-01_01.png'
baseurl: ''
disqus: 'demowebsite'
weibo_username: nengwuzhi
email: 'miandenglu@protonmail.com'
paginate: 10
paginate_path: /page/:num/
all_dir: all/
categories_dir: categories
author_dir: /author
include: ["_pages"]


authors:  
  author1:
    name: 能无知
    site: https://nengwuzhi.github.io/
    avatar: assets/images/avatar1.png
    bio: "言有宗，事有君。夫唯无知，是以我不知！"
    Source-Title: "道可道，非常道。"
    email: mailto:author1thunaseer@gmail.com
    twitter: https://twitter.com/nengwuzhi
    instagram: https://www.instagram.com/nengwuzhi/  
  author2:
    name: 能无为
    site: https://nengwuwei.com/
    avatar: assets/images/avatar2.png
    bio: "一切有为法，如梦幻泡影，如露亦如电，应作如是观。"
    Source-Title: "应无所住，而生其心。"
    email: mailto:author2chemmengath@gmail.com
    twitter: https://twitter.com/nengwuwei
    instagram: https://www.instagram.com/nengwuwei/
# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts/gallery"
    values:
      category: gallery 
      layout: alt
      
  # all pages
  - scope:
      path: "_posts/博客"
    values:
      category: 博客
      layout: post     
      
# Syntax
markdown: kramdown
highlighter: rouge

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
